name: CI

on:
  workflow_dispatch:
    inputs:
      stage:
        type: choice
        description: stage name
        options: 
          - dev
          - uat
          - prod
        default: dev

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.stage }}
    
    env: 
      my_secret: ${{ secrets.MY_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          echo "running a job in dev environment!"
          echo "$my_secret"
          