# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      env: # Or as an environment variable
        my_secret: ${{ secrets.MY_SECRET }}
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "running a job in dev environment!"
          echo "$my_secret"
  UAT_ENV:
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "running a job in uat environment!"
          echo "$my_secret"
        
  PROD_ENV:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "running a job in prod environment!"
          echo "$my_secret"
