name: CI

on:
  workflow_dispatch:

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: 
      name: ${{GITHUB_REF##*/}}
    
    env: 
      my_secret: ${{ secrets.MY_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          echo "running a job in dev environment!"
          echo "my branch is: ${GITHUB_REF##*/}"
          echo ${{ env.my_secret == 'prod' && 'is prod' || 'not prod' }}
          echo ${{ env.my_secret == 'dev' && 'is dev' || 'not dev' }}
          echo ${{ env.my_secret == 'uat' && 'is uat' || 'not uat' }}

          